### ISSUE TITLE
Wrong define name in  I2C_24LC1025 

### ISSUE THREAD

**Issue by whams** [RobTillaart/I2C_24LC1025#3]
In I2C_24LC1025 .h and .cpp there seems to be a small mistake in the naming of a define:
#define I2C_DEVICESIZE_24LC512      131072   should probably be:
#define I2C_DEVICESIZE_24LC1025      131072

If you include only I2C_24LC1025 .h in your project there is no problem, but if you also include I2C_EEPROM.h the compiler will churn out a warning as you are now clobbering an already defined macro - which is not what you would want.

**Comment by RobTillaart** [comment]
Thanks for pointing out.  Never used them in combination.
I will look into this asap.

**Comment by RobTillaart** [comment]
@whams 
Had another look, and it looks like it is indeed wrong - 
The define was already in the first version so I assume "copy and paste" to keep the interface identical copied a bit too much. 

Made a develop branch with a fix  + some minor edits - https://github.com/RobTillaart/I2C_24LC1025/tree/develop 
Can you test that branch for me as I have no hardware nearby.

Thanks,
Rob

**Comment by whams** [comment]
@RobTillaart 
I've copied your dev branch cpp and header files of I2C_24LC1025 over my local install, added

// 1. select ROM_TYPE from I2C_24LC1025 or I2C_eeprom e.g. 24LC256 
// 2. select EEPROM specific buffer size, also used as array size (must be const)
//    should be page_buffer_size minus 2/3 bytes (for NUL and MSB and LSB addresses??) ??
#ifndef ROM_TYPE
#define ROM_TYPE I2C_eeprom
#define BUFFER_SIZE 30
////// OR
//#define ROM_TYPE I2C_24LC1025
//#define BUFFER_SIZE 125
#endif

to my own header file and 

// instantiate the EEPROM - we have a 24LC256 or another 16 bit rom
I2C_eeprom eeprom((uint8_t) EEPROM_ADDRESS, (uint32_t) I2C_DEVICESIZE_24LC256);
////// OR
// instantiate the EEPROM - we have a 24LC1025 or another 32 bit rom
//I2C_24LC1025 eeprom((uint8_t) EEPROM_ADDRESS);

to my main.cpp

and while switching between ROM chip on the board (and above comments)  I had no problem or warning on clean compiling my own project.

I've tested instantiation of both ROMs, then setting up the I2C connection and write/readByte of a single byte, write/readBlock of a 20-byte char array, and then write/readBlock of variously sized other char arrays just under or over the respective pagesizes (for the corresponding I2C_BUFFERSIZE), which on inspection of the relevant part of the memdump of the ROM  all produced/failed as expected, that is, char arrays not exceeding the pagesize minus 2 turn out fine, bigger ones produce some strange effects that I can neither explain nor describe simply.  As long as I don't exceed the I2C_BUFFERSIZE minus 2 or 3 I seem to be fine.

I still have to do some extra testing on the readBlock readback of correctly written (as I can see in the memdump) data on the ROMs, but my conclusion is that your fixes in the dev branch are all fine and good to go.
Thanks a lot for bringing us this I2C eeprom library, I've tried o few others, but yours works best for me.

**Comment by RobTillaart** [comment]
thanks for testing!
released 0.1.5
